apiVersion: apps/v1
kind: Deployment
metadata:
  name: tarik-app
  labels:
    app: tarik-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tarik-app
  template:
    metadata:
      name: tarik-app
      labels:
        app: tarik-app
    spec:
      containers:
        - name: tarik-app
          image: nginx
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: tarik-service
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: tarik-app
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tarik-ingress
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-southeast-1:105638660012:certificate/6b3a98b6-4490-4e0d-b5c9-5aea7be9ed52
spec:
  ingressClassName: alb
  rules:
    - host: ostad-app.rfft.nl
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tarik-service
                port:
                  number: 80
